bookmark/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', show, name="show"),
    path('new/', new, name="new"),
    path('edit/<int:pk>', edit, name="edit"),
    path('delete/<int:pk>', delete, name="delete"),
]

main/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    site_name = models.CharField(max_length=50)
    site_url = models.CharField(max_length=1000)

main/forms.py
from django import forms
from .models import Bookmark

class BookmarkForm(forms.ModelForm):
    site_name = forms.CharField(label="사이트 명")
    site_url = forms.CharField(label="사이트 주소")
    
    class Meta :
        model = Bookmark
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Bookmark
from .forms import BookmarkForm

# Create your views here.

def show(request):
    bookmarks = Bookmark.objects.all()

    return render(request, 'show.html', {'bookmarks':bookmarks})

def new(request):
    if request.method == 'POST':
        form = BookmarkForm(request.POST)
        if form.is_valid():
            bookmark = Bookmark()
            bookmark.site_name = form.cleaned_data['site_name']
            bookmark.site_url = form.cleaned_data['site_url']
            bookmark.save()
            return redirect('main:show')
    
    else:
        form = BookmarkForm()

    return render(request, 'new.html', {'form': form})

def edit(request, pk):
    bookmark = get_object_or_404(Bookmark, pk=pk)

    if request.method == 'POST':
        form = BookmarkForm(request.POST, instance=bookmark)
        if form.is_valid():
            bookmark.site_name = form.cleaned_data['site_name']
            bookmark.site_url = form.cleaned_data['site_url']
            bookmark.save()
            return redirect('main:show')
    
    else:
        form = BookmarkForm(instance=bookmark)

    return render(request, 'new.html', {'bookmark':bookmark,'form': form})

def delete(request, pk):
    bookmark = get_object_or_404(Bookmark, pk=pk)
    if request.method == 'POST':
        bookmark.delete()
        return redirect('main:show')

bookmark/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>BOOKMARK</title>
    
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

main/templates/base.html
{% extends 'base.html %}

main/templates/edit.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block content %}

<div>
    <h1 class="display-3">BOOK-MARK</h1>
    <br>
    <div>
        <button class="btn btn-light"><a href="{% url 'main:show'%}">HOME</a></button>
    </div>
    <br>
</div>

<div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
        </table>
        <input type="submit" value="수정">
    </form>
</div>

{% endblock %}

main/templates/new.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block content %}

<div>
    <h1 class="display-3">BOOK-MARK</h1>
    <br>
    <div>
        
        <button class="btn btn-light"><a href="{% url 'main:show'%}">HOME</a></button>
    </div>
    <br>
</div>

<div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-light">추가</button>
    </form>
</div>

{% endblock %}

main/templates/show.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block content %}

<div>
    <h1 class="display-3">BOOK-MARK</h1>
    <br>
    <div>
        <button type="submit" class="btn btn-light">
        <a href="{% url 'main:new'%}">CREATE</a></button>
    </div>
    <br>
</div>

<div>
    {% if bookmarks %}
    {% for bookmark in bookmarks %}
    <div class="card ">
        <h5 class="card-header">{{bookmark.site_name}}</h5>
        <div class="card-body">
            <h4 class="card-title">{{bookmark.site_url}}</h4>
            <button class="btn btn-light">
                <a href="{% url 'main:edit' bookmark.id %}" >edit</a>
            </button>
            <form action="{% url 'main:delete' bookmark.id %}" method='POST'>
                {% csrf_token %}
                <input type="submit" class="btn btn-light" value="delete">
            </form>
        </div>
      </div>

    {% endfor %}

    {% else %}
    <div>
        <p>북마크가 비어있어요 CREATE 필요</p>
    </div>
    {% endif %}
    
</div>
{% endblock %}